# Generated by Django 4.2.1 on 2023-05-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='imageUri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestinfo',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
