# Generated by Django 4.2.1 on 2023-05-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentGenerator', '0003_rename_imageuri_requestinfo_image_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
